import * as pulumi from "@pulumi/pulumi";
import * as utilities from "@kengachu-pulumi/azure-native-core/utilities";
import * as types from "./types";
/**
 * Gets a single custom assessment automation by name for the provided subscription and resource group.
 *
 * Uses Azure REST API version 2021-07-01-preview.
 */
export function getCustomAssessmentAutomation(args: GetCustomAssessmentAutomationArgs, opts?: pulumi.InvokeOptions): Promise<GetCustomAssessmentAutomationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("azure-native:security:getCustomAssessmentAutomation", {
        "customAssessmentAutomationName": args.customAssessmentAutomationName,
        "resourceGroupName": args.resourceGroupName,
    }, opts);
}

export interface GetCustomAssessmentAutomationArgs {
    /**
     * Name of the Custom Assessment Automation.
     */
    customAssessmentAutomationName: string;
    /**
     * The name of the resource group within the user's subscription. The name is case insensitive.
     */
    resourceGroupName: string;
}

/**
 * Custom Assessment Automation
 */
export interface GetCustomAssessmentAutomationResult {
    /**
     * The assessment metadata key used when an assessment is generated for this assessment automation.
     */
    readonly assessmentKey?: string;
    /**
     * GZip encoded KQL query representing the assessment automation results required.
     */
    readonly compressedQuery?: string;
    /**
     * The description to relate to the assessments generated by this assessment automation.
     */
    readonly description?: string;
    /**
     * The display name of the assessments generated by this assessment automation.
     */
    readonly displayName?: string;
    /**
     * Resource Id
     */
    readonly id: string;
    /**
     * Resource name
     */
    readonly name: string;
    /**
     * The remediation description to relate to the assessments generated by this assessment automation.
     */
    readonly remediationDescription?: string;
    /**
     * The severity to relate to the assessments generated by this assessment automation.
     */
    readonly severity?: string;
    /**
     * Relevant cloud for the custom assessment automation.
     */
    readonly supportedCloud?: string;
    /**
     * Azure Resource Manager metadata containing createdBy and modifiedBy information.
     */
    readonly systemData: types.outputs.SystemDataResponse;
    /**
     * Resource type
     */
    readonly type: string;
}
/**
 * Gets a single custom assessment automation by name for the provided subscription and resource group.
 *
 * Uses Azure REST API version 2021-07-01-preview.
 */
export function getCustomAssessmentAutomationOutput(args: GetCustomAssessmentAutomationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCustomAssessmentAutomationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("azure-native:security:getCustomAssessmentAutomation", {
        "customAssessmentAutomationName": args.customAssessmentAutomationName,
        "resourceGroupName": args.resourceGroupName,
    }, opts);
}

export interface GetCustomAssessmentAutomationOutputArgs {
    /**
     * Name of the Custom Assessment Automation.
     */
    customAssessmentAutomationName: pulumi.Input<string>;
    /**
     * The name of the resource group within the user's subscription. The name is case insensitive.
     */
    resourceGroupName: pulumi.Input<string>;
}