import * as pulumi from "@pulumi/pulumi";
import * as utilities from "@kengachu-pulumi/azure-native-core/utilities";
import * as types from "./types";
/**
 * Get a specific custom recommendation for the requested scope by customRecommendationName
 *
 * Uses Azure REST API version 2024-08-01.
 */
export function getCustomRecommendation(args: GetCustomRecommendationArgs, opts?: pulumi.InvokeOptions): Promise<GetCustomRecommendationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("azure-native:security:getCustomRecommendation", {
        "customRecommendationName": args.customRecommendationName,
        "scope": args.scope,
    }, opts);
}

export interface GetCustomRecommendationArgs {
    /**
     * Name of the Custom Recommendation.
     */
    customRecommendationName: string;
    /**
     * The fully qualified Azure Resource manager identifier of the resource.
     */
    scope: string;
}

/**
 * Custom Recommendation
 */
export interface GetCustomRecommendationResult {
    /**
     * The assessment metadata key used when an assessment is generated for this Recommendation.
     */
    readonly assessmentKey: string;
    /**
     * The Azure API version of the resource.
     */
    readonly azureApiVersion: string;
    /**
     * List of all standard supported clouds.
     */
    readonly cloudProviders?: string[];
    /**
     * The description to relate to the assessments generated by this Recommendation.
     */
    readonly description?: string;
    /**
     * The display name of the assessments generated by this Recommendation.
     */
    readonly displayName?: string;
    /**
     * Fully qualified resource ID for the resource. E.g. "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}"
     */
    readonly id: string;
    /**
     * The name of the resource
     */
    readonly name: string;
    /**
     * KQL query representing the Recommendation results required.
     */
    readonly query?: string;
    /**
     * The remediation description to relate to the assessments generated by this Recommendation.
     */
    readonly remediationDescription?: string;
    /**
     * The severity to relate to the assessments generated by this Recommendation.
     */
    readonly securityIssue?: string;
    /**
     * The severity to relate to the assessments generated by this Recommendation.
     */
    readonly severity?: string;
    /**
     * Azure Resource Manager metadata containing createdBy and modifiedBy information.
     */
    readonly systemData: types.outputs.SystemDataResponse;
    /**
     * The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
     */
    readonly type: string;
}
/**
 * Get a specific custom recommendation for the requested scope by customRecommendationName
 *
 * Uses Azure REST API version 2024-08-01.
 */
export function getCustomRecommendationOutput(args: GetCustomRecommendationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCustomRecommendationResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("azure-native:security:getCustomRecommendation", {
        "customRecommendationName": args.customRecommendationName,
        "scope": args.scope,
    }, opts);
}

export interface GetCustomRecommendationOutputArgs {
    /**
     * Name of the Custom Recommendation.
     */
    customRecommendationName: pulumi.Input<string>;
    /**
     * The fully qualified Azure Resource manager identifier of the resource.
     */
    scope: pulumi.Input<string>;
}