import * as enums from "./enums";
import * as pulumi from "@pulumi/pulumi";
    /**
     * The properties specific to an Enterprise Channel Node.
     */
    export interface EnterpriseChannelNodeResponse {
        /**
         * The location of the Enterprise Channel Node.
         */
        azureLocation: string;
        /**
         * The sku of the Enterprise Channel Node.
         */
        azureSku: string;
        /**
         * Id of Enterprise Channel Node. This is generated by the Bot Framework.
         */
        id: string;
        /**
         * The name of the Enterprise Channel Node.
         */
        name: string;
        /**
         * The current state of the Enterprise Channel Node.
         */
        state?: string;
    }

    /**
     * The parameters to provide for the Enterprise Channel.
     */
    export interface EnterpriseChannelPropertiesResponse {
        /**
         * The nodes associated with the Enterprise Channel.
         */
        nodes: EnterpriseChannelNodeResponse[];
        /**
         * The current state of the Enterprise Channel.
         */
        state?: string;
    }

    /**
     * Extra Parameters specific to each Service Provider
     */
    export interface ServiceProviderParameterResponse {
        /**
         * Default Name for the Service Provider
         */
        default: string;
        /**
         * Description of the Service Provider
         */
        description: string;
        /**
         * Display Name of the Service Provider
         */
        displayName: string;
        /**
         * Help Url for the  Service Provider
         */
        helpUrl: string;
        /**
         * Name of the Service Provider
         */
        name: string;
        /**
         * Type of the Service Provider
         */
        type: string;
    }

    /**
     * The Object used to describe a Service Provider supported by Bot Service
     */
    export interface ServiceProviderPropertiesResponse {
        /**
         * Display Name of the Service Provider
         */
        devPortalUrl: string;
        /**
         * Display Name of the Service Provider
         */
        displayName: string;
        /**
         * Display Name of the Service Provider
         */
        iconUrl: string;
        /**
         * Id for Service Provider
         */
        id: string;
        /**
         * The list of parameters for the Service Provider
         */
        parameters?: ServiceProviderParameterResponse[];
        /**
         * Display Name of the Service Provider
         */
        serviceProviderName: string;
    }

    /**
     * Service Provider Definition
     */
    export interface ServiceProviderResponse {
        /**
         * The Properties of a Service Provider Object
         */
        properties?: ServiceProviderPropertiesResponse;
    }

    /**
     * The SKU of the cognitive services account.
     */
    export interface SkuResponse {
        /**
         * The sku name
         */
        name: string;
        /**
         * Gets the sku tier. This is based on the SKU name.
         */
        tier: string;
    }
