import * as enums from "./enums";
import * as pulumi from "@pulumi/pulumi";
    /**
     * Properties specific to the grafana resource.
     */
    export interface ManagedGrafanaPropertiesArgs {
        autoGeneratedDomainNameLabelScope?: pulumi.Input<string | enums.AutoGeneratedDomainNameLabelScope>;
        /**
         * Provisioning state of the resource.
         */
        provisioningState?: pulumi.Input<string | enums.ProvisioningState>;
        zoneRedundancy?: pulumi.Input<string | enums.ZoneRedundancy>;
    }

    /**
     * The managed identity of a resource.
     */
    export interface ManagedIdentityArgs {
        /**
         * The type 'SystemAssigned, UserAssigned' includes both an implicitly created identity and a set of user assigned identities. The type 'None' will remove any identities from the resource.
         */
        type?: pulumi.Input<string | enums.IdentityType>;
        /**
         * Dictionary of user assigned identities.
         */
        userAssignedIdentities?: pulumi.Input<pulumi.Input<string>[]>;
    }

    export interface ResourceSkuArgs {
        name: pulumi.Input<string>;
    }
