import * as enums from "./enums";
import * as pulumi from "@pulumi/pulumi";
    /**
     * Properties specific to the grafana resource.
     */
    export interface ManagedGrafanaPropertiesResponse {
        autoGeneratedDomainNameLabelScope?: string;
        /**
         * The endpoint of the Grafana instance.
         */
        endpoint: string;
        /**
         * The Grafana software version.
         */
        grafanaVersion: string;
        /**
         * Provisioning state of the resource.
         */
        provisioningState?: string;
        zoneRedundancy?: string;
    }

    /**
     * The managed identity of a resource.
     */
    export interface ManagedIdentityResponse {
        /**
         * The principal id of the system assigned identity.
         */
        principalId: string;
        /**
         * The tenant id of the system assigned identity.
         */
        tenantId: string;
        /**
         * The type 'SystemAssigned, UserAssigned' includes both an implicitly created identity and a set of user assigned identities. The type 'None' will remove any identities from the resource.
         */
        type?: string;
        /**
         * Dictionary of user assigned identities.
         */
        userAssignedIdentities?: {[key: string]: UserAssignedIdentityResponse};
    }

    export interface ResourceSkuResponse {
        name: string;
    }

    export interface SystemDataResponse {
        createdAt?: string;
        createdBy?: string;
        /**
         * The type of identity that created the resource.
         */
        createdByType?: string;
        lastModifiedAt?: string;
        lastModifiedBy?: string;
        lastModifiedByType?: string;
    }

    export interface UserAssignedIdentityResponse {
        /**
         * The client id of user assigned identity.
         */
        clientId: string;
        /**
         * The principal id of user assigned identity.
         */
        principalId: string;
    }
