import * as enums from "./enums";
import * as pulumi from "@pulumi/pulumi";
export namespace dashboard {
    /**
     * Integrations for Azure Monitor Workspace.
     */
    export interface AzureMonitorWorkspaceIntegrationResponse {
        /**
         * The resource Id of the connected Azure Monitor Workspace.
         */
        azureMonitorWorkspaceResourceId?: string;
    }

    /**
     * GrafanaIntegrations is a bundled observability experience (e.g. pre-configured data source, tailored Grafana dashboards, alerting defaults) for common monitoring scenarios.
     */
    export interface GrafanaIntegrationsResponse {
        azureMonitorWorkspaceIntegrations?: AzureMonitorWorkspaceIntegrationResponse[];
    }

    /**
     * Properties specific to the grafana resource.
     */
    export interface ManagedGrafanaPropertiesResponse {
        /**
         * The api key setting of the Grafana instance.
         */
        apiKey?: string;
        /**
         * Scope for dns deterministic name hash calculation.
         */
        autoGeneratedDomainNameLabelScope?: string;
        /**
         * Whether a Grafana instance uses deterministic outbound IPs.
         */
        deterministicOutboundIP?: string;
        /**
         * The endpoint of the Grafana instance.
         */
        endpoint: string;
        /**
         * GrafanaIntegrations is a bundled observability experience (e.g. pre-configured data source, tailored Grafana dashboards, alerting defaults) for common monitoring scenarios.
         */
        grafanaIntegrations?: GrafanaIntegrationsResponse;
        /**
         * The Grafana software version.
         */
        grafanaVersion: string;
        /**
         * List of outbound IPs if deterministicOutboundIP is enabled.
         */
        outboundIPs: string[];
        /**
         * The private endpoint connections of the Grafana instance.
         */
        privateEndpointConnections: PrivateEndpointConnectionResponse[];
        /**
         * Provisioning state of the resource.
         */
        provisioningState: string;
        /**
         * Indicate the state for enable or disable traffic over the public interface.
         */
        publicNetworkAccess?: string;
        /**
         * The zone redundancy setting of the Grafana instance.
         */
        zoneRedundancy?: string;
    }

    /**
     * Managed service identity (system assigned and/or user assigned identities)
     */
    export interface ManagedServiceIdentityResponse {
        /**
         * The service principal ID of the system assigned identity. This property will only be provided for a system assigned identity.
         */
        principalId: string;
        /**
         * The tenant ID of the system assigned identity. This property will only be provided for a system assigned identity.
         */
        tenantId: string;
        /**
         * Type of managed service identity (where both SystemAssigned and UserAssigned types are allowed).
         */
        type: string;
        /**
         * The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests.
         */
        userAssignedIdentities?: {[key: string]: UserAssignedIdentityResponse};
    }

    /**
     * The Private Endpoint Connection resource.
     */
    export interface PrivateEndpointConnectionResponse {
        /**
         * The private endpoint connection group ids.
         */
        groupIds?: string[];
        /**
         * Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
         */
        id: string;
        /**
         * The name of the resource
         */
        name: string;
        /**
         * The resource of private end point.
         */
        privateEndpoint?: PrivateEndpointResponse;
        /**
         * A collection of information about the state of the connection between service consumer and provider.
         */
        privateLinkServiceConnectionState: PrivateLinkServiceConnectionStateResponse;
        /**
         * The provisioning state of the private endpoint connection resource.
         */
        provisioningState: string;
        /**
         * Azure Resource Manager metadata containing createdBy and modifiedBy information.
         */
        systemData: SystemDataResponse;
        /**
         * The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
         */
        type: string;
    }

    /**
     * The Private Endpoint resource.
     */
    export interface PrivateEndpointResponse {
        /**
         * The ARM identifier for Private Endpoint
         */
        id: string;
    }

    /**
     * A collection of information about the state of the connection between service consumer and provider.
     */
    export interface PrivateLinkServiceConnectionStateResponse {
        /**
         * A message indicating if changes on the service provider require any updates on the consumer.
         */
        actionsRequired?: string;
        /**
         * The reason for approval/rejection of the connection.
         */
        description?: string;
        /**
         * Indicates whether the connection has been Approved/Rejected/Removed by the owner of the service.
         */
        status?: string;
    }

    export interface ResourceSkuResponse {
        name: string;
    }

    /**
     * Metadata pertaining to creation and last modification of the resource.
     */
    export interface SystemDataResponse {
        /**
         * The timestamp of resource creation (UTC).
         */
        createdAt?: string;
        /**
         * The identity that created the resource.
         */
        createdBy?: string;
        /**
         * The type of identity that created the resource.
         */
        createdByType?: string;
        /**
         * The timestamp of resource last modification (UTC)
         */
        lastModifiedAt?: string;
        /**
         * The identity that last modified the resource.
         */
        lastModifiedBy?: string;
        /**
         * The type of identity that last modified the resource.
         */
        lastModifiedByType?: string;
    }

    /**
     * User assigned identity properties
     */
    export interface UserAssignedIdentityResponse {
        /**
         * The client ID of the assigned identity.
         */
        clientId: string;
        /**
         * The principal ID of the assigned identity.
         */
        principalId: string;
    }

    export namespace v20210901preview {
        /**
         * Properties specific to the grafana resource.
         */
        export interface ManagedGrafanaPropertiesResponse {
            autoGeneratedDomainNameLabelScope?: string;
            /**
             * The endpoint of the Grafana instance.
             */
            endpoint: string;
            /**
             * The Grafana software version.
             */
            grafanaVersion: string;
            /**
             * Provisioning state of the resource.
             */
            provisioningState?: string;
            zoneRedundancy?: string;
        }

        /**
         * The managed identity of a resource.
         */
        export interface ManagedIdentityResponse {
            /**
             * The principal id of the system assigned identity.
             */
            principalId: string;
            /**
             * The tenant id of the system assigned identity.
             */
            tenantId: string;
            /**
             * The type 'SystemAssigned, UserAssigned' includes both an implicitly created identity and a set of user assigned identities. The type 'None' will remove any identities from the resource.
             */
            type?: string;
            /**
             * Dictionary of user assigned identities.
             */
            userAssignedIdentities?: {[key: string]: v20210901preview.UserAssignedIdentityResponse};
        }

        export interface ResourceSkuResponse {
            name: string;
        }

        export interface SystemDataResponse {
            createdAt?: string;
            createdBy?: string;
            /**
             * The type of identity that created the resource.
             */
            createdByType?: string;
            lastModifiedAt?: string;
            lastModifiedBy?: string;
            lastModifiedByType?: string;
        }

        export interface UserAssignedIdentityResponse {
            /**
             * The client id of user assigned identity.
             */
            clientId: string;
            /**
             * The principal id of user assigned identity.
             */
            principalId: string;
        }

    }

    export namespace v20220801 {
        /**
         * Integrations for Azure Monitor Workspace.
         */
        export interface AzureMonitorWorkspaceIntegrationResponse {
            /**
             * The resource Id of the connected Azure Monitor Workspace.
             */
            azureMonitorWorkspaceResourceId?: string;
        }

        /**
         * GrafanaIntegrations is a bundled observability experience (e.g. pre-configured data source, tailored Grafana dashboards, alerting defaults) for common monitoring scenarios.
         */
        export interface GrafanaIntegrationsResponse {
            azureMonitorWorkspaceIntegrations?: v20220801.AzureMonitorWorkspaceIntegrationResponse[];
        }

        /**
         * Properties specific to the grafana resource.
         */
        export interface ManagedGrafanaPropertiesResponse {
            /**
             * The api key setting of the Grafana instance.
             */
            apiKey?: string;
            /**
             * Scope for dns deterministic name hash calculation.
             */
            autoGeneratedDomainNameLabelScope?: string;
            /**
             * Whether a Grafana instance uses deterministic outbound IPs.
             */
            deterministicOutboundIP?: string;
            /**
             * The endpoint of the Grafana instance.
             */
            endpoint: string;
            /**
             * GrafanaIntegrations is a bundled observability experience (e.g. pre-configured data source, tailored Grafana dashboards, alerting defaults) for common monitoring scenarios.
             */
            grafanaIntegrations?: v20220801.GrafanaIntegrationsResponse;
            /**
             * The Grafana software version.
             */
            grafanaVersion: string;
            /**
             * List of outbound IPs if deterministicOutboundIP is enabled.
             */
            outboundIPs: string[];
            /**
             * The private endpoint connections of the Grafana instance.
             */
            privateEndpointConnections: v20220801.PrivateEndpointConnectionResponse[];
            /**
             * Provisioning state of the resource.
             */
            provisioningState: string;
            /**
             * Indicate the state for enable or disable traffic over the public interface.
             */
            publicNetworkAccess?: string;
            /**
             * The zone redundancy setting of the Grafana instance.
             */
            zoneRedundancy?: string;
        }

        /**
         * Managed service identity (system assigned and/or user assigned identities)
         */
        export interface ManagedServiceIdentityResponse {
            /**
             * The service principal ID of the system assigned identity. This property will only be provided for a system assigned identity.
             */
            principalId: string;
            /**
             * The tenant ID of the system assigned identity. This property will only be provided for a system assigned identity.
             */
            tenantId: string;
            /**
             * Type of managed service identity (where both SystemAssigned and UserAssigned types are allowed).
             */
            type: string;
            /**
             * The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests.
             */
            userAssignedIdentities?: {[key: string]: v20220801.UserAssignedIdentityResponse};
        }

        /**
         * The Private Endpoint Connection resource.
         */
        export interface PrivateEndpointConnectionResponse {
            /**
             * The private endpoint connection group ids.
             */
            groupIds?: string[];
            /**
             * Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
             */
            id: string;
            /**
             * The name of the resource
             */
            name: string;
            /**
             * The resource of private end point.
             */
            privateEndpoint?: v20220801.PrivateEndpointResponse;
            /**
             * A collection of information about the state of the connection between service consumer and provider.
             */
            privateLinkServiceConnectionState: v20220801.PrivateLinkServiceConnectionStateResponse;
            /**
             * The provisioning state of the private endpoint connection resource.
             */
            provisioningState: string;
            /**
             * Azure Resource Manager metadata containing createdBy and modifiedBy information.
             */
            systemData: v20220801.SystemDataResponse;
            /**
             * The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
             */
            type: string;
        }

        /**
         * The Private Endpoint resource.
         */
        export interface PrivateEndpointResponse {
            /**
             * The ARM identifier for Private Endpoint
             */
            id: string;
        }

        /**
         * A collection of information about the state of the connection between service consumer and provider.
         */
        export interface PrivateLinkServiceConnectionStateResponse {
            /**
             * A message indicating if changes on the service provider require any updates on the consumer.
             */
            actionsRequired?: string;
            /**
             * The reason for approval/rejection of the connection.
             */
            description?: string;
            /**
             * Indicates whether the connection has been Approved/Rejected/Removed by the owner of the service.
             */
            status?: string;
        }

        export interface ResourceSkuResponse {
            name: string;
        }

        /**
         * Metadata pertaining to creation and last modification of the resource.
         */
        export interface SystemDataResponse {
            /**
             * The timestamp of resource creation (UTC).
             */
            createdAt?: string;
            /**
             * The identity that created the resource.
             */
            createdBy?: string;
            /**
             * The type of identity that created the resource.
             */
            createdByType?: string;
            /**
             * The timestamp of resource last modification (UTC)
             */
            lastModifiedAt?: string;
            /**
             * The identity that last modified the resource.
             */
            lastModifiedBy?: string;
            /**
             * The type of identity that last modified the resource.
             */
            lastModifiedByType?: string;
        }

        /**
         * User assigned identity properties
         */
        export interface UserAssignedIdentityResponse {
            /**
             * The client ID of the assigned identity.
             */
            clientId: string;
            /**
             * The principal ID of the assigned identity.
             */
            principalId: string;
        }

    }
}
