import * as pulumi from "@pulumi/pulumi";
import * as utilities from "@kengachu-pulumi/azure-native-core/utilities";
// Export members:
export { ListBillingAccountInvoiceSectionsByCreateSubscriptionPermissionArgs, ListBillingAccountInvoiceSectionsByCreateSubscriptionPermissionResult, ListBillingAccountInvoiceSectionsByCreateSubscriptionPermissionOutputArgs } from "./listBillingAccountInvoiceSectionsByCreateSubscriptionPermission";
export const listBillingAccountInvoiceSectionsByCreateSubscriptionPermission: typeof import("./listBillingAccountInvoiceSectionsByCreateSubscriptionPermission").listBillingAccountInvoiceSectionsByCreateSubscriptionPermission = null as any;
export const listBillingAccountInvoiceSectionsByCreateSubscriptionPermissionOutput: typeof import("./listBillingAccountInvoiceSectionsByCreateSubscriptionPermission").listBillingAccountInvoiceSectionsByCreateSubscriptionPermissionOutput = null as any;
utilities.lazyLoad(exports, ["listBillingAccountInvoiceSectionsByCreateSubscriptionPermission","listBillingAccountInvoiceSectionsByCreateSubscriptionPermissionOutput"], () => require("./listBillingAccountInvoiceSectionsByCreateSubscriptionPermission"));