name: Publish packages to npm

on:
  workflow_dispatch:

  # schedule:
  #   - cron: "50 */3 * * 1,3,5"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: |
          make node_modules/ci

      - name: Run tests
        run: |
          bun test
        working-directory: scripts

      - name: Publish packages
        run: |
          bun scripts/publish.ts

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
