name: Publish packages to npm

on:
  workflow_dispatch:

  schedule:
    - cron: "50 * * * 1,2"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: |
          make node_modules/ci

      - name: Setup Bun
        run: |
          bun install
        working-directory: scripts

      - name: Publish packages
        run: |
          bun scripts/publish-packages-for-current-hour.ts --yes

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
