name: Build and publish packages

on:
  workflow_dispatch:

jobs:
  prepare-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: |
          make node_modules/ci

      - name: Publish packages
        run: |
          pnpm publish -r
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
