name: Update version if needed

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-pulumi-repo-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Check if @pulumi/azure-native has been updated
        continue-on-error: true
        run: |
          make check-version

      - run: |
          git config --global user.email "${{ vars.GIT_EMAIL }}"
          git config --global user.name "${{ vars.GIT_NAME }}"

      - name: Generate new versions for packages without cache and commit
        run: |
          make generate-packages/push
