name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/**
      - pnpm-lock.yaml
  pull_request:
    branches:
      - main

jobs:
  build-and-run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Install dependencies
        run: |
          make node_modules/ci

      - name: Run tests
        run: |
          bun test
        working-directory: scripts

      - name: Lint
        run: |
          make lint
