name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v2.*
      - v3.*

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-and-run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
      #
      # - name: Run tests
      #   run: |
      #     bun test
      #   working-directory: scripts

      - name: Lint
        run: |
          make lint

      - name: Publish packages
        run: |
          make publish
