name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v2.*

jobs:
  build-and-run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Run tests
        run: |
          bun test
        working-directory: scripts

      - name: Lint
        run: |
          make lint

      - name: Publish packages
        run: |
          make publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
