name: Release pull requests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  run-if:
    if: startsWith(github.head_ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Version release branch detected"

  run-checks:
    needs: run-if
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

  approve-merge:
    needs: run-checks
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Add release tag
        run: |
          TAG=$(jq .version packages/core/package.json -r)
          git tag "v$TAG"
          git push --tags

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --delete-branch
